INSERT into menu  (id, ten_mon , gia_ban , loai  , hinh_anh) VALUES (4, 'Lẩu Thái Hải Sản', 150000, 'MonAn','images/product/lauchuacay.jpg');
INSERT into menu  (id, ten_mon , gia_ban , loai  , hinh_anh) VALUES (5, 'Phở Bò', 30000, 'MonAn', 'images/product/phobo.jpg');
INSERT into menu  (id, ten_mon , gia_ban , loai  , hinh_anh) VALUES (6, 'Đùi Gà', 50000, 'MonAn', 'images/product/duiga.jpg');
INSERT into menu  (id, ten_mon , gia_ban , loai  , hinh_anh) VALUES (7, 'Hambuger Bò', 50000, 'MonAn', 'images/product/hamberger.jpg');
INSERT into menu  (id, ten_mon , gia_ban , loai  , hinh_anh) VALUES (8, 'Nước Ép Dưa Hấu', 20000, 'NuocUong', 'images/product/duahau.jpg');
INSERT into menu  (id, ten_mon , gia_ban , loai  , hinh_anh) VALUES (9, 'Nước Ép Dứa', 20000, 'NuocUong', 'images/product/dua.jpg');
INSERT into menu  (id, ten_mon , gia_ban , loai  , hinh_anh) VALUES (10, 'CocaCola', 15000, 'NuocUong', 'images/product/coca.jpg');
INSERT into menu  (id, ten_mon , gia_ban , loai  , hinh_anh) VALUES (11, 'Nước Suối', 6000, 'NuocUong', 'images/product/loc.jpg');
INSERT into menu  (id, ten_mon , gia_ban , loai  , hinh_anh) VALUES (12, '7Up', 10000, 'NuocUong', 'images/product/7Up.jpg');
INSERT into menu  (id, ten_mon , gia_ban , loai  , hinh_anh) VALUES (13, 'Monster', 10000, 'NuocUong', 'images/product/monster.jpg');
INSERT into menu  (id, ten_mon , gia_ban , loai  , hinh_anh) VALUES (14, 'Phở Bò', 30000, 'AnNhieu', 'images/phobo.jpg');
INSERT into menu  (id, ten_mon , gia_ban , loai  , hinh_anh) VALUES (15, 'Bún Bò', 30000, 'AnNhieu', 'images/bunbo.jpg');
INSERT into menu  (id, ten_mon , gia_ban , loai  , hinh_anh) VALUES (1, 'Lẩu Thái Hải Sản', 150000, 'AnNhieu', 'images/lauchuacay.jpg');
INSERT into menu  (id, ten_mon , gia_ban , loai  , hinh_anh) VALUES (16, 'Đùi gà', 50000, 'AnNhieu', 'images/duiga.jpg');
INSERT into menu  (id, ten_mon , gia_ban , loai  , hinh_anh) VALUES (17, 'Bún Bò', 30000, 'MonAn', 'images/bunbo.jpg');
INSERT into menu  (id, ten_mon , gia_ban , loai  , hinh_anh) VALUES (3, 'Cơm Tấm', 30000, 'AnNhieu', 'images/comtam.jpg');
INSERT into menu  (id, ten_mon , gia_ban , loai  , hinh_anh) VALUES (2, 'Cơm Tấm', 30000, 'MonAn', 'images/product/comtam2.jpg');